@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "User")

Container(reverseProxy, "Reverse proxy", "Nginx")

System_Boundary(followingSystem, "Following system") {
Container(followingService, "Following Service", "Go", "Manages users followings", $tags="webApp")
ContainerDb(followingDatabase, "Following database", "Postgresql", "Stores followings",  $tags="db")
}

System_Boundary(userSystem, "User system") {
}

Rel(user, reverseProxy, "CRUD operations for followings", "REST")
Rel(reverseProxy, followingService, "CRUD operations for followings", "REST")
Rel(followingService, followingDatabase, "Get/Update followings")
Rel(followingService, userSystem, "Get users info (username, avatar) when getting followings list")
@enduml
