@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "User")

Container(reverseProxy, "Reverse proxy", "Nginx")

System_Boundary(feedSystem, "Feed system") {
Container(feedService, "Feed Service", "Go", "Get/Generate personalized feed", $tags="webApp")
ContainerDb(feedDatabase, "Feed database", "Postgresql", "Stores feeds",  $tags="db")
ContainerDb(feedCache, "Feed cache", "Redis", "Stores feeds",  $tags="db")
}

System_Boundary(followingSystem, "Following system") {
}

System_Boundary(postSystem, "Post system") {
}

Rel(user, reverseProxy, "Get personalized feed", "REST")
Rel(reverseProxy, feedService, "Get personalized feed", "REST")
Rel(feedService, feedDatabase, "Get/Update personalized feed")
Rel(feedService, feedCache, "Initial getting feed for user")
Rel(feedService, followingSystem, "Get followings")
Rel(feedService, postSystem, "Get posts info")
@enduml
