@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "User")

Container(reverseProxy, "Reverse proxy", "Nginx")

System_Boundary(userSystem, "User system") {
Container(userService, "User Service", "Go", "Manages users accounts", $tags="webApp")
ContainerDb(userDatabase, "User database", "Postgresql", "Stores users",  $tags="db")
}

Rel(user, reverseProxy, "CRUD operations for users accounts", "REST")
Rel(reverseProxy, userService, "CRUD operations for users accounts", "REST")
Rel(userService, userDatabase, "Get/Update users data")
@enduml
